FROM node:10 AS builde

WORKDIR /app

COPY . /app

RUN npm build

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/build .

CMD [ "nginx", "-g", "daemon off;" ]
